"""로컬 LLM(LM Studio) 연동 — 자연어 프롬프트 생성.

Qt와 무관한 코어. UI(`ui/assistant_dialog.py`)는 여기의 순수 로직을 백그라운드
스레드에서 호출한다. WD14 자동 태깅(`core/wd14_tagger.py`) 경로와 같은 구조다:
가용성 판정(`runtime_error`) → 무거운 작업 본체(`generate`) → 결과를 프롬프트에
반영하는 순수 함수(`apply_generated_prompt`).
"""

from __future__ import annotations

from .lmstudio_client import (
    DEFAULT_HOST,
    DEFAULT_SYSTEM_PROMPT,
    DEFAULT_TIMEOUT,
    LENGTH_LONG,
    LENGTH_MEDIUM,
    LENGTH_SHORT,
    OUTPUT_LENGTHS,
    PROMPT_STYLES,
    STYLE_DANBOORU,
    STYLE_NATURAL,
    SYSTEM_PROMPT_DANBOORU,
    SYSTEM_PROMPT_NATURAL,
    CancelCheck,
    LMStudioCancelled,
    LMStudioConfig,
    LMStudioConnectionError,
    LMStudioError,
    LMStudioNoModelError,
    LMStudioNotInstalled,
    LMStudioPromptGenerator,
    LMStudioResponseError,
    LMStudioTimeoutError,
    LMStudioVisionUnsupported,
    PromptResult,
    max_tokens_for_length,
    runtime_error,
    system_prompt_for_style,
)
from .parsing import parse_prompt_result
from .prompt_apply import apply_generated_prompt
from .prompt_config import (
    CONFIG_VERSION,
    DEFAULT_CONFIG_FILENAME,
    LENGTH_KEYS,
    MESSAGE_KEYS,
    STYLE_KEYS,
    PromptConfig,
    PromptConfigError,
    StylePrompt,
    config_to_dict,
    default_prompt_config,
    default_prompt_config_path,
    load_prompt_config,
    load_prompt_config_or_default,
    merge_prompt_config,
    write_prompt_config,
)

__all__ = [
    "CONFIG_VERSION",
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_HOST",
    "DEFAULT_SYSTEM_PROMPT",
    "DEFAULT_TIMEOUT",
    "LENGTH_KEYS",
    "LENGTH_LONG",
    "LENGTH_MEDIUM",
    "LENGTH_SHORT",
    "MESSAGE_KEYS",
    "OUTPUT_LENGTHS",
    "PROMPT_STYLES",
    "STYLE_DANBOORU",
    "STYLE_KEYS",
    "STYLE_NATURAL",
    "SYSTEM_PROMPT_DANBOORU",
    "SYSTEM_PROMPT_NATURAL",
    "CancelCheck",
    "LMStudioCancelled",
    "LMStudioConfig",
    "LMStudioConnectionError",
    "LMStudioError",
    "LMStudioNoModelError",
    "LMStudioNotInstalled",
    "LMStudioPromptGenerator",
    "LMStudioResponseError",
    "LMStudioTimeoutError",
    "LMStudioVisionUnsupported",
    "PromptConfig",
    "PromptConfigError",
    "PromptResult",
    "StylePrompt",
    "apply_generated_prompt",
    "config_to_dict",
    "default_prompt_config",
    "default_prompt_config_path",
    "load_prompt_config",
    "load_prompt_config_or_default",
    "merge_prompt_config",
    "max_tokens_for_length",
    "parse_prompt_result",
    "runtime_error",
    "system_prompt_for_style",
    "write_prompt_config",
]
